all: ssearch subsum tsp btree tsp_dp

ssearch: ssearch.c
	gcc ssearch.c -o ssearch

subsum: subsum.c
	gcc subsum.c -o subsum

tsp: tsp.c
	gcc tsp.c -o tsp

btree: btree.c
	gcc btree.c -o btree

tsp_dp: tsp_dp.c
	gcc tsp_dp.c -o tsp_dp

clean:
	rm -rf *.o ssearch subsum tsp btree tsp_dp
