all: enclosing_parser number_pairs

enclosing_parser: enclosing_parser.c
	gcc enclosing_parser.c -o enclosing_parser

number_pairs: number_pairs.c
	gcc number_pairs.c -o number_pairs

clean:
	rm -rf enclosing_parser number_pairs

